#include "builder.hpp"

#include <algorithm>
#include <filesystem>
#include <format>
#include <fstream>
#include <span>
#include <string>
#include <vector>

#include "command.hpp"
#include "sharedlib.hpp"

static bool createCMakeLists(const std::filesystem::path& buildDir, std::span<const std::filesystem::path> extensions) {
	std::ofstream outFile(buildDir / "CMakeLists.txt");
	if(!outFile.is_open()) return false;

	outFile << "#################################################\n";
	outFile << "## This file is automatically generated by Rat ##\n";
	outFile << "## Any changes will be discarded               ##\n";
	outFile << "#################################################\n";
	outFile << "cmake_minimum_required(VERSION 3.25)\n";
	outFile << "project(ratengine)\n";
	outFile << "\n";
	outFile << "option(RAT_BUILD_EDITOR \"Build the project to be attached to the editor\" OFF)\n";
	outFile << "\n";
	outFile << "find_package(rat)\n";
	outFile << "\n";
	outFile << "if(RAT_BUILD_EDITOR)\n";
	outFile << "  add_library(ratengine SHARED .rat/main.cpp)\n";
	outFile << "  target_compile_definitions(ratengine PUBLIC RAT_EDITOR)\n";
	outFile << "else()\n";
	outFile << "  add_executable(ratengine .rat/main.cpp)\n";
	outFile << "endif()\n";
	outFile << "\n";
	outFile << "add_custom_command(\n";
	outFile << "  TARGET ratengine\n";
	outFile << "  POST_BUILD COMMAND ${CMAKE_COMMAND} -E copy $<TARGET_FILE:ratengine> ${CMAKE_CURRENT_SOURCE_DIR}/.rat\n";
	outFile << "  VERBATIM\n";
	outFile << ")\n";
	outFile << "\n";
	for(const auto& extension : extensions)
		outFile << "add_subdirectory(" << std::filesystem::relative(extension, buildDir).generic_string() << " ${CMAKE_BINARY_DIR}/"
		        << extension.filename().string() << ")\n";

	return true;
}

static bool createEngineMain(const std::filesystem::path& buildDir, std::span<const std::filesystem::path> extensions) {
	std::ofstream outFile(buildDir / "main.cpp");
	if(!outFile.is_open()) return false;

	outFile << "/////////////////////////////////////////////////\n";
	outFile << "// This file is automatically generated by Rat //\n";
	outFile << "// Any changes will be discarded               //\n";
	outFile << "/////////////////////////////////////////////////\n";
	outFile << "\n";
	outFile << "#ifdef RAT_EDITOR\n";
	outFile << "\t#ifdef _WIN32\n";
	outFile << "\t\t#define RAT_EXPORT __declspec(dllexport)\n";
	outFile << "\t#else\n";
	outFile << "\t\t#if defined(__GNUC__) && __GNUC__ >= 4\n";
	outFile << "\t\t\t#define RAT_EXPORT __attribute__((visibility(\"default\")))\n";
	outFile << "\t\t#else\n";
	outFile << "\t\t\t#define RAT_EXPORT\n";
	outFile << "\t\t#endif\n";
	outFile << "\t#endif\n";
	outFile << "#else\n";
	outFile << "\t#define RAT_EXPORT\n";
	outFile << "#endif\n";
	outFile << "\n";
	for(const auto& extension : extensions) outFile << "void " << extension.filename().string() << "Init();\n";
	outFile << "\n";
	outFile << "extern \"C\" RAT_EXPORT int ratEngineMain() {\n";
	for(const auto& extension : extensions) outFile << "\t" << extension.filename().string() << "Init();\n";
	outFile << "\treturn 0;\n";
	outFile << "}\n";
	outFile << "\n";
	outFile << "#ifndef RAT_EDITOR\n";
	outFile << "\tint main() { return ratEngineMain(); }\n";
	outFile << "#endif\n";
	return true;
}

static std::vector<std::filesystem::path> loadExtensions(const std::filesystem::path& root) {
	std::vector<std::filesystem::path> extensions;
	for(const auto& entry : std::filesystem::directory_iterator(root / "extensions"))
		if(entry.is_directory()) extensions.emplace_back(entry.path());
	return extensions;
}

bool linkEngine(const char* projectPath) {
#ifdef _WIN32
	const char* engineName = "ratengine.dll";
#else
	const char* engineName = "libratengine.so";
#endif

	std::filesystem::path projPath = std::filesystem::absolute(projectPath);
	if(!projPath.has_parent_path()) return false;
	std::filesystem::path root = projPath.parent_path();
	std::filesystem::path enginePath = root / ".rat" / engineName;

	SharedLib engine = OpenLibrary(enginePath);
	if(!engine) return false;

	auto main = GetSymbol<void()>(engine, "ratEngineMain");
	if(!main) return false;
	main();

	return true;
}

bool generateBuildFiles(const char* projectPath) {
	std::filesystem::path projPath = std::filesystem::absolute(projectPath);
	if(!projPath.has_parent_path()) return false;
	std::filesystem::path root = projPath.parent_path();
	std::filesystem::path ratDir = root / ".rat";
	std::vector<std::filesystem::path> extensions = loadExtensions(root);
	std::filesystem::create_directories(ratDir);
	if(!createCMakeLists(root, extensions)) return false;
	if(!createEngineMain(ratDir, extensions)) return false;
	return true;
}

bool buildEngine(const char* projectPath, bool editor) {
	std::filesystem::path projPath = std::filesystem::absolute(projectPath);
	if(!projPath.has_parent_path()) return false;
	std::filesystem::path root = projPath.parent_path();
	std::filesystem::path ratDir = root / ".rat";
	std::filesystem::path buildDir = ratDir / (editor ? "build" : "export");

	runCommand(
	    R"(cmake "{}" -B "{}" -G Ninja -DRAT_BUILD_EDITOR={} -DCMAKE_EXPORT_COMPILE_COMMANDS=ON)",
	    root.generic_string(),
	    buildDir.generic_string(),
	    editor ? "ON" : "OFF"
	);
	runCommand(R"(cmake --build "{}")", buildDir.generic_string());

	return true;
}
