if(NOT TARGET glfw)
  set(GLFW_BUILD_DOCS OFF CACHE STRING "" FORCE)
  add_subdirectory(external/glfw EXCLUDE_FROM_ALL SYSTEM)
endif()

add_subdirectory(external/glm EXCLUDE_FROM_ALL SYSTEM)
add_subdirectory(external/glad EXCLUDE_FROM_ALL SYSTEM)
add_subdirectory(core)

set(SLANG_ENABLE_REPLAYER OFF CACHE STRING "" FORCE)
set(SLANG_ENABLE_EXAMPLES OFF CACHE STRING "" FORCE)
set(SLANG_ENABLE_TESTS OFF CACHE STRING "" FORCE)
set(SLANG_ENABLE_GFX OFF CACHE STRING "" FORCE)
set(SLANG_ENABLE_SLANGD OFF CACHE STRING "" FORCE)
set(SLANG_ENABLE_SLANGC OFF CACHE STRING "" FORCE)
set(SLANG_ENABLE_SLANGI OFF CACHE STRING "" FORCE)
set(SLANG_ENABLE_TIME_TRACE OFF CACHE STRING "" FORCE)
set(SLANG_ENABLE_COVERAGE OFF CACHE STRING "" FORCE)
set(SLANG_ENABLE_ASAN OFF CACHE STRING "" FORCE)
set(SLANG_ENABLE_IR_BREAK_ALLOC OFF CACHE STRING "" FORCE)
set(SLANG_ENABLE_FULL_IR_VALIDATION OFF CACHE STRING "" FORCE)
add_subdirectory(external/slang EXCLUDE_FROM_ALL SYSTEM)