name: Build

on:
  push:
    branches: [main]
  pull_request:

jobs:
  rat:
    name: Rat
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        build-type: [Debug, Release]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - name: Install Dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt update
          sudo apt install libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libxext-dev libwayland-dev libxkbcommon-dev
      - uses: turtlesec-no/get-ninja@1.1
      - uses: ilammy/msvc-dev-cmd@v1
        if: runner.os == 'Windows'
      - name: Build Project
        run: |
          if [[ "${runner.os}" == "Linux" ]] ; then
            export CC clang
            export CXX clang++
          fi

          if [[ "${{ runner.os }}" == "Windows" ]]; then
            COMPILE_FLAGS="/WX"
          else
            COMPILE_FLAGS="-Werror"
          fi

          cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=${{ matrix.build-type }} -DCMAKE_CXX_FLAGS="$COMPILE_FLAGS"
          cmake --build build --target rat --parallel $(nproc)

