name: Build

on:
  push:
    branches: [main]
  pull_request:

jobs:
  engine:
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        build-type: [Debug, Release]

    steps:
      - uses: actions/checkout@v4
        with:
          submodules: 'recursive'
      - name: Install Dependencies
        if: runner.os == 'Linux'
        run: |
          sudo apt update
          sudo apt install libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libxext-dev libwayland-dev libxkbcommon-dev
      - uses: turtlesec-no/get-ninja@main
      - uses: ilammy/msvc-dev-cmd@v1
        if: runner.os == 'Windows'
      - name: Build Rat
        shell: bash
        run: |
          if [[ "${{ runner.os }}" == "Linux" ]] ; then
            export CC=clang
            export CXX=clang++
          fi

          cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=${{ matrix.build-type }} -DCMAKE_COMPILE_WARNING_AS_ERROR=On
          cmake --build build --target rat --parallel $(nproc)
      - uses: actions/upload-artifact@v7
        with:
          name: ${{ matrix.os }}_${{ matrix.build-type }}
          path: build/
          retention-days: 1

  samples:
    needs: engine
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [windows-latest, ubuntu-latest]
        rat-build-type: [Editor, Development, Release]
        build-type: [Debug, Release]

    steps:
    - uses: actions/checkout@v4
      with:
        submodules: 'recursive'
    - uses: actions/download-artifact@v8
      with:
        name: ${{ matrix.os }}_Release
        path: build/
    - name: Install Dependencies
      if: runner.os == 'Linux'
      run: |
        sudo apt update
        sudo apt install libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libxext-dev libwayland-dev libxkbcommon-dev
    - name: Build Samples
      shell: bash
      run: |
        echo "${{ github.workspace }}/build/rat" >> $GITHUB_PATH

        if [[ "${{ runner.os }}" == "Linux" ]] ; then
          export CC=clang
          export CXX=clang++
        fi

        for sample in samples/*/; do
          cd $sample
          cmake -B build -G Ninja -DCMAKE_BUILD_TYPE=${{ matrix.build-type }} -DRAT_BUILD_TYPE=${{ matrix.rat-build-type }} -DCMAKE_COMPILE_WARNING_AS_ERROR=On
          cmake --build build --target ratengine --parallel $(nproc)
        done
