name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    name: Build Project
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        preset: [debug, release]

    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: sudo apt update && sudo apt install libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libxext-dev libwayland-dev libxkbcommon-dev
      - name: Build project
        run: |
          mkdir build
          cmake \
            --preset ${{ matrix.preset }} \
            -DCMAKE_C_COMPILER=clang \
            -DCMAKE_CXX_COMPILER=clang++ \
            -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
            -DCMAKE_CXX_FLAGS="-Werror" \
            -B build
          cmake --build build --parallel $(nproc)
      - uses: actions/upload-artifact@v7
        with:
          name: build-linux-${{ matrix.preset }}
          path: build/
          retention-days: 1

  linting:
    name: Linter
    needs: build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        preset: [debug, release]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v8
        with:
          name: build-linux-${{ matrix.preset }}
          path: build/
      - uses: cpp-linter/cpp-linter-action@v2
        id: linter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          style: 'file'
          tidy-checks: ''
          version: '19'
          database: 'build'
          step-summary: true
          files-changed-only: true
          ignore: 'external|build'
      - name: Get include-what-you-use
        run: git clone https://github.com/include-what-you-use/include-what-you-use.git
      - name: Run include-what-you-use
        run: include-what-you-use/iwyu_tool.py -p build -j $(nproc) --ignore_re='(external|build)' | include-what-you-use/fix_includes.py --dry_run
      - if: steps.linter.outputs.checks-failed > 0
        run: exit 1
