name: CI

on:
  push:
    branches: [main]
  pull_request:

jobs:
  build:
    name: Build Project
    runs-on: ubuntu-latest
    
    strategy:
      matrix:
        preset: [Debug, Release]

    steps:
      - uses: actions/checkout@v4
      - name: Install dependencies
        run: |
          sudo apt update
          sudo apt install libxrandr-dev libxinerama-dev libxcursor-dev libxi-dev libxext-dev libwayland-dev libxkbcommon-dev iwyu
      - name: Build project
        run: |
          cmake \
            -DCMAKE_BUILD_TYPE=${{ matrix.preset }} \
            -DCMAKE_C_COMPILER=clang \
            -DCMAKE_CXX_COMPILER=clang++ \
            -DCMAKE_EXPORT_COMPILE_COMMANDS=ON \
            -DCMAKE_CXX_FLAGS="-Werror" \
            -DRAT_USE_IWYU=ON \
            -B build
          cmake --build build --parallel $(nproc)
      - uses: actions/upload-artifact@v7
        with:
          name: Linux${{ matrix.preset }}
          path: build/
          retention-days: 1

  linting:
    name: Linter
    needs: build
    runs-on: ubuntu-latest

    strategy:
      matrix:
        preset: [Debug, Release]

    steps:
      - uses: actions/checkout@v4
      - uses: actions/download-artifact@v8
        with:
          name: Linux${{ matrix.preset }}
          path: build/
      - uses: cpp-linter/cpp-linter-action@v2
        id: linter
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          style: 'file'
          tidy-checks: ''
          version: '19'
          database: 'build'
          step-summary: true
          files-changed-only: true
          ignore: 'build|engine'
      - if: steps.linter.outputs.checks-failed > 0
        run: exit 1
